### ISSUE TITLE
Couldn't find any configuration for the '' repo.

### ISSUE THREAD

**Issue by delphiactual** [lumoslabs/txgh#67]
I am running the docker container with the following command
` sudo docker run -p 9292:9292 -e "TXGH_CONFIG=raw://$(cat ~/txgh.yml)" -d quay.io/lumoslabs/txgh:latest`

Contents of `~/txgh.yml`
```
---
github:
  repos:
    delphiactual/DIM:
      api_token: token
      api_username: username
      branch: webpack-i18n
      push_source_to: destiny-item-manager
      webhook_secret: secret
transifex:
  projects:
    destiny-item-manager:
      api_password: password
      api_username: username
      auto_delete_resources: "false"
      push_translations_to: webpack-i18n
      tx_config: "git://.tx/config"
      webhook_secret: secret
```

When testing the `GitHub` Webhook I receive the following error from `txgh`:
`[{"error":"Internal server error: Couldn't find any configuration for the '' repo."}]`

Is there any way to attach to the container and put `txgh.yml` directly inside the container?
